### ISSUE TITLE
Qwik Error: useClientEffectQrl is not a function

### ISSUE THREAD

**Issue by aleksandar-p4** [qwik-design/qwik-rive#4]
Hi, while attempting to utilize the `qwik-rive` package according to the provided documentation, the mentioned error occurred on `npm run dev`. It seems to stem from a function call, `useClientEffectQrl`, not being recognized as a valid function.

`[vite] Internal server error: __vite_ssr_import_3__.useClientEffectQrl is not a function`

Edit. Resolved by updating the package to the latest Qwik version.

**Comment by ImmortalMaize** [comment]
I have the same error. Imports say the package may need to update its typings or package.json. How did you go about updating the package?

I'm using the latest version of Qwik as of a few days ago.

![image](https://github.com/qwikverse/qwik-rive/assets/68474964/335f1365-1202-43be-9c96-8cd53f2d3b63)

**Comment by aleksandar-p4** [comment]
@ImmortalMaize Sorry for late reply, check out this PR, it's just been merged to the main branch so it should fix the problem thanks to @mrhoodz. https://github.com/qwikverse/qwik-rive/pull/3
